// <auto-generated />
using System;
using LookForRoad.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LookForRoad.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20201115165908_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LookForRoad.Data.Models.Road", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("HowManyPlaces")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<long>("Telephone")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("datafrom")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isFav")
                        .HasColumnType("bit");

                    b.Property<string>("place")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Road");
                });
#pragma warning restore 612, 618
        }
    }
}
